# Generated by Django 3.0.2 on 2020-01-29 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('plastic', models.CharField(choices=[('PLA', 'PLA'), ('PET', 'PET'), ('ABS', 'ABS'), ('ASA', 'ASA'), ('TPU', 'TPU')], default='PLA', max_length=50)),
                ('density', models.FloatField()),
                ('diameter', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filaments.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Spool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('mass_net', models.FloatField()),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filaments.OwnerProfile')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filaments.Variant')),
            ],
        ),
        migrations.CreateModel(
            name='MassChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('mass_net', models.FloatField()),
                ('spool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filaments.Spool')),
            ],
        ),
    ]
